name: Check Access Token Age

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 9 * * 1'  # Every Monday at 09:00 UTC
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/check_secret_age.yaml'

permissions: read-all

jobs:
  check-secret-age:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: gh_app_token
        with:
          app-id: ${{ vars.APP_CHECK_AGE_ID }}
          private-key: ${{ secrets.APP_CHECK_AGE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Get Secret last updated time
        id: check_secret_age
        env:
          GH_TOKEN: ${{ steps.gh_app_token.outputs.token }}
          SECRET_NAME: TEST_SECRET
        run: |
          set -euo pipefail

          threshold=20 # minutes
          valid_secret=""

          response=$(curl -sL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/orgs/${{ github.repository_owner }}/actions/secrets/$SECRET_NAME)
          
          updated_at=$(echo "$response" | jq -r '.updated_at')                    
          
          updated_seconds=$(date -d "$updated_at" +%s)
          now_seconds=$(date +%s)
          
          secret_age_minutes=$(( (now_seconds - updated_seconds) / 60 ))

          echo "Secret Age is: $secret_age_minutes minutes"

          if [[ $secret_age_minutes -lt $threshold ]]; then
            echo "Secret is updated within the last ${threshold} minutes."
            valid_secret="true"     
          else
            echo "Secret is older than ${threshold} minutes."
            valid_secret="false"
          fi
          
          echo "valid_secret=$valid_secret" >> $GITHUB_OUTPUT

      - name: Check existing Banner Status
        id: current_banner
        env:
          GH_TOKEN: ${{ steps.gh_app_token.outputs.token }}
        run: |
          set -euo pipefail
          
          status="false"
          announcement=$(curl -sL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/orgs/${{ github.repository_owner }}/announcement | jq -r '.announcement // empty')
          
          if [[ $announcement == "**GitHub Issue Detected:** TF Modules may be affected" ]]; then
            echo "Existing banner detected"
            status="true"
          fi

          echo "status=$status" >> $GITHUB_OUTPUT

      - name: Create Banner if Secret is old and no existing banner
        if: steps.current_banner.outputs.status == 'false' && steps.check_secret_age.outputs.valid_secret == 'false'
        env:
          GH_TOKEN: ${{ steps.gh_app_token.outputs.token }}
        run: |
          set -euo pipefail

          curl -sL \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/orgs/${{ github.repository_owner }}/announcement \
            -d '{"announcement":"**GitHub Issue Detected:** TF Modules may be affected"}'

      - name: Remove Banner if Secret is updated and banner exists
        if: steps.current_banner.outputs.status == 'true' && steps.check_secret_age.outputs.valid_secret == 'true'
        env:
          GH_TOKEN: ${{ steps.gh_app_token.outputs.token }}
        run: |
          set -euo pipefail
          
          curl -sL \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/orgs/${{ github.repository_owner }}/announcement
