name: Check Access Token Age

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 9 * * 1'  # Every Monday at 09:00 UTC
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/check_secret_age.yaml'

permissions: read-all

jobs:
  check-secret-age:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: gh_app_token
        with:
          app-id: ${{ vars.APP_CHECK_AGE_ID }}
          private-key: ${{ secrets.APP_CHECK_AGE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Get Secret last updated time
        env:
          GH_TOKEN: ${{ steps.gh_app_token.outputs.token }}
          SECRET_NAME: TEST_SECRET
        run: |

          threshold=20 # minutes
          
          response=$(curl -sL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/orgs/${{ github.repository_owner }}/actions/secrets/$SECRET_NAME)
          
          updated_at=$(echo "$response" | jq -r '.updated_at')                    
          
          updated_seconds=$(date -d "$updated_at" +%s)
          now_seconds=$(date +%s)
          
          secret_age_seconds=$((now_seconds - updated_seconds))
          secret_age_minutes=$((secret_age_seconds / 60))
                    
          echo "Secret Age is: $secret_age_minutes minutes"

          if [[ $secret_age_minutes -lt $threshold ]]; then
            echo "Secret is updated within the last ${threshold} minutes."
          else
            echo "Secret is older than ${threshold} minutes."
            echo "Send notification to Slack or email here."
          fi
          echo "SecretAge: $updated_at"
